### ISSUE TITLE
Error Class 'NZTim\Mailchimp\MailchimpServiceProvider' not found

### ISSUE THREAD

**Issue by mattiak14** [rainlab/mailchimp-plugin#29]
Hello,
I don't understand why on the frontend of my site after installing the mailchimp plugin I have this exception!
"Class 'NZTim\Mailchimp\MailchimpServiceProvider' not found"
and if I uninstall it, after I clean the cache every now and then the same error occurs again!
Somebody help me, please?
thank you

**Comment by LukeTowers** [comment]
Github issues really isn't the place for questions like this. Please use one of the many other avenues available instead of submitting new issues for your questions.

Slack: https://octobercms-slack.herokuapp.com/
Forum: https://octobercms.com/forum
StackOverflow: https://stackoverflow.com/questions/tagged/octobercms
IRC: #october on Freenode or https://octobercms.com/chat
